version: 4.3.0.{build}
configuration: Release
platform: x64
build:
  project: LDView.vcxproj
  verbosity: minimal

image:
- Visual Studio 2015
- Visual Studio 2017
- ubuntu1804

install:
- sh: sudo apt-get update; sudo apt-get install -y -qq libqt4-dev libqt4-opengl-dev libpng-dev libjpeg-dev libtinyxml-dev cmake kdelibs5-dev libgl1-mesa-dev libosmesa6-dev build-essential debhelper lintian fakeroot

build_script:
- sh: cd QT;./makedeb
- cmd: msbuild "C:\projects\ldview\LDView.vcxproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

skip_commits:
  files:
    - MacOSX/
