version: 4.3.0.{build}
configuration: Release
platform: x64
build:
  project: LDView.vcxproj
  verbosity: minimal

image:
- Visual Studio 2015
- Visual Studio 2017
- ubuntu1804

install:
- sh: sudo apt install -y -qq libqt4-dev libqt4-opengl-dev libpng-dev libjpeg-dev libtinyxml-dev

build_script:
- sh: cd QT;qmake -spec linux-g++-64;make
- cmd: msbuild "C:\projects\ldview\LDView.vcxproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

skip_commits:
  files:
    - MacOSX/
