version: 2.1

jobs:
  build-ubuntu:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Install build dependency
          command: ./QT/docker/install-devel-packages.sh
      - run:
          name: Build LDView
          command: cd QT ; sed -i 's/kdelibs5-dev//g' debian/control ; ./makedeb -qt5
          
  build-fedora:
    docker:
      - image: fedora:33
    steps:
      - checkout
      - run:
          name: Install build dependency
          command: ./QT/docker/install-devel-packages.sh
      - run:
          name: Build LDView
          command: cd QT ; ./makerpm
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-ubuntu
      - build-fedora
